name: "Get Environment Variables"
description: "Retrieves environment variables for end-to-end tests"

inputs:
  version:
    description: "Custom version to use"
    required: true
  token:
    description: "Cloud access token"
    required: true
  repo_token:
    description: "GitHub repository token"
    required: true
  project:
    description: "Project name"
    required: true

outputs:
  IS_OLD_VERSION:
    description: "Whether the version is old"
    value: ${{ steps.get-environment-variables.outputs.IS_OLD_VERSION }}

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: pnpm
    - name: install dependencies
      working-directory: .github/workflows
      shell: bash
      run: pnpm install
    - name: Get environment variables
      id: get-environment-variables
      shell: bash
      env:
        REPO_TOKEN: ${{ inputs.repo_token }}
        TOKEN: ${{ inputs.token }}
      run: |
        node .github/workflows/testsHelpers/getEnvironmentVariables.js \
          --version ${{ inputs.version }} \
          --token "$TOKEN" \
          --repo_token "$REPO_TOKEN" \
          --project "${{ inputs.project }}"
