name: Saleor CLI login
description: Saleor CLI login to staging Saleor Cloud
inputs:
  token:
    description: "Cloud access token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Write config file
      shell: bash
      id: write-config-file
      env:
        ACCESS_TOKEN: ${{ inputs.token }}
      run: |
        jq --null-input \
           --arg token "Token $ACCESS_TOKEN" \
           '{"token":$token,"telemetry":"false","saleor_env":"staging","cloud_api_url":"https://staging-cloud.saleor.io/platform/api","organization_slug":"saleor","organization_name":"Saleor"}' > ~/.config/saleor.json
