name: Push flaky test report
description: Push flaky test report to qa repository
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Push Test Report
      shell: bash
      run: |
        export GITHUB_TOKEN=$( \
            curl --request GET --url ${{ inputs.VAULT_URL}} --header "Authorization: JWT ${{ inputs.VAULT_JWT }}" | jq -r .token \
          )
        node .github/workflows/send-report-to-repo.js \
      env:
        VAULT_URL: ${{ inputs.VAULT_URL }}
        VAULT_JWT: ${{ inputs.VAULT_JWT }}
      if: always()

inputs:
  VAULT_URL:
    description: "Vault URL for GitHub token"
    required: true
  VAULT_JWT:
    description: "Vault JWT for GitHub token"
    required: true
