name: Push flaky test report
description: Push flaky test report to qa repository
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Push Test Report
      shell: bash
      run: |
        export GITHUB_TOKEN=$( \
            curl --request GET --url ${{ secrets.VAULT_URL}} --header "Authorization: JWT ${{ secrets.VAULT_JWT }}" | jq -r .token \
          )
        node .github/workflows/send-report-to-repo.js 
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      if: always()
