version: 2
updates:
  - target-branch: "master"
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "saleor-frontend"
    allowed_updates:
      - match:
          update_type: "security"

  - target-branch: "3.0"
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "saleor-frontend"
    allowed_updates:
      - match:
          update_type: "security"
