FROM node:14
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG APP_MOUNT_URL
ARG API_URL
ARG STATIC_URL
ENV API_URL ${API_URL:-http://localhost:8000/graphql/}
ENV APP_MOUNT_URL ${APP_MOUNT_URL:-/}
ENV STATIC_URL ${STATIC_URL:-/}

EXPOSE 9000
CMD npm start -- --host 0.0.0.0
