blockExoticSubdeps: true

minimumReleaseAge: 720 # 12h
minimumReleaseAgeExclude:
  - "@saleor/app-sdk"

trustPolicy: no-downgrade
trustPolicyExclude:
  - vite@6.4.1
  # due to "@types/node@20.19.31"
  - "undici-types@6.21.0"
  # due to eslint-plugin-import@2.32.0
  - "semver@6.3.1"
  # due to @graphql-tools/url-loader@8.0.33
  - "jose@4.15.9"
  - "@graphql-tools/executor-graphql-ws@2.0.7"
  - "@graphql-tools/executor-http@1.3.3"
  - "@graphql-tools/wrap@10.1.4"
  - "@graphql-tools/delegate@10.2.23"
  - "@graphql-tools/batch-execute@9.0.19"
  # due to @graphql-codegen/import-types-preset@2.2.6
  - "ua-parser-js@1.0.41"

packages:
  - "."

# Keeps src/ and .github/workflows directories separated
# as they are independent from one to another.
recursiveInstall: false
sharedWorkspaceLockfile: false

onlyBuiltDependencies:
  - "@sentry/cli"
  - "@swc/core"
  - "core-js"
  - "esbuild"
  - "fsevents"
  - "oxc-resolver"
  - "sharp"

overrides:
  "@babel/runtime@<7.26.10": ">=7.26.10"
  "lodash@<4.17.23": ">=4.17.23"
  "dompurify@<3.2.4": ">=3.2.4"
  "glob@>=10.3.7 <=11.0.3": ">=11.1.0"
  "js-yaml@>=4.0.0 <4.1.1": ">=4.1.1"
  "js-yaml@<3.14.2": ">=3.14.2"
  "preact@>=10.28.0 <10.28.2": ">=10.28.2"
  "read-yaml-file@<2.0.0": ">=2.1.0"
  "tmp@<0.2.4": ">=0.2.4"
  "vite@>=6.0.0 <6.4.1": ">=6.4.1"
  "ws@>=8.0.0 <8.17.1": ">=8.17.1"
