import { defineMessages } from "react-intl";

export const messages = defineMessages({
  manual: {
    id: "vCIhp5",
    defaultMessage: "Manual code",
    description: "voucher add-code menu: enter one code by hand",
  },
  manualDescription: {
    id: "i+v5kJ",
    defaultMessage: "Enter a single code",
    description: "voucher add-code menu hint for manual entry",
  },
  autoGenerate: {
    id: "QjaBoT",
    defaultMessage: "Generate codes",
    description: "voucher add-code menu: bulk generate",
  },
  autoGenerateDescription: {
    id: "rAWeFD",
    defaultMessage: "Create multiple codes at once",
    description: "voucher add-code menu hint for bulk generate",
  },
  addCode: {
    id: "6xNl6V",
    defaultMessage: "Add code",
  },
});
