import { iconSize, iconStrokeWidthBySize } from "@dashboard/components/icons";
import { type MenuItem, SubMenu } from "@dashboard/components/SubMenu";
import { Box, Button, Popover } from "@saleor/macaw-ui-next";
import { Plus } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import { useIntl } from "react-intl";

import { messages } from "./messages";

interface VoucherCodesAddButtonProps {
  onMultiCodesGenerate: () => void;
  onSingleCodesGenerate: () => void;
  /** Reserves header layout while the page shell loads — no menu. */
  disabled?: boolean;
}

export const VoucherCodesAddButton = ({
  onMultiCodesGenerate,
  onSingleCodesGenerate,
  disabled = false,
}: VoucherCodesAddButtonProps): JSX.Element => {
  const [isSubMenuOpen, setSubMenuOpen] = useState(false);
  const intl = useIntl();
  const handleMultupleCodesGenerate = useCallback(() => {
    onMultiCodesGenerate();
    setSubMenuOpen(false);
  }, [onMultiCodesGenerate]);
  const handleManualCodeGenerate = useCallback(() => {
    onSingleCodesGenerate();
    setSubMenuOpen(false);
  }, [onSingleCodesGenerate]);
  const subMenuItems = useMemo<MenuItem[]>(
    () => [
      {
        id: "manual",
        title: intl.formatMessage(messages.manual),
        description: intl.formatMessage(messages.manualDescription),
        onClick: handleManualCodeGenerate,
      },
      {
        id: "auto-generate-codes",
        title: intl.formatMessage(messages.autoGenerate),
        description: intl.formatMessage(messages.autoGenerateDescription),
        onClick: handleMultupleCodesGenerate,
      },
    ],
    [handleMultupleCodesGenerate, handleManualCodeGenerate, intl],
  );

  if (disabled) {
    return (
      <Button data-test-id="add-code-button" type="button" size="small" disabled>
        <Plus size={iconSize.small} strokeWidth={iconStrokeWidthBySize.small} />
        {intl.formatMessage(messages.addCode)}
      </Button>
    );
  }

  return (
    <Popover open={isSubMenuOpen} onOpenChange={setSubMenuOpen}>
      <Popover.Trigger>
        <Button data-test-id="add-code-button" type="button" size="small">
          <Plus size={iconSize.small} strokeWidth={iconStrokeWidthBySize.small} />
          {intl.formatMessage(messages.addCode)}
        </Button>
      </Popover.Trigger>
      <Popover.Content align="end">
        <Box marginTop={1}>
          <SubMenu menuItems={subMenuItems} />
        </Box>
      </Popover.Content>
    </Popover>
  );
};
