name: Prepare instance
description: Prepare cloud instance for testing
inputs:
  STRATEGY:
    description: "How to create the new instance (create|reload)"
    required: false
    default: "create"
  CLI_TOKEN:
    description: "Saleor cli token"
    required: true
  BASE_URL:
    description: "Dashboard base url"
    required: true
  API_URL:
    description: "API url"
    required: true
  POOL_NAME:
    description: "The name of the instance"
    required: true
  POOL_INSTANCE:
    description: "The full URL of the instance"
    required: true
  BACKUP_ID:
    description: "The id of backup"
    required: true
  SALEOR_CLOUD_SERVICE:
    description: "Which saleor cloud service to use"
    required: true
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
    - name: Saleor login
      uses: ./.github/actions/cli-login
      with:
        token: ${{ inputs.CLI_TOKEN }}

    - name: Instance check
      if: ${{ inputs.STRATEGY == 'reload' }}
      shell: bash
      id: instance_check
      env:
        INSTANCE_NAME: ${{ inputs.POOL_NAME }}
      run: |
        set +o pipefail
        INSTANCE_KEY=$(pnpx saleor env show "$INSTANCE_NAME" --json | jq .key)
        echo "INSTANCE_KEY=$INSTANCE_KEY" >> $GITHUB_OUTPUT

    - name: Reload snapshot
      shell: bash
      continue-on-error: true
      if: ${{ steps.instance_check.outputs.INSTANCE_KEY }}
      env:
        BACKUP_ID: ${{ inputs.BACKUP_ID }}
        INSTANCE_NAME: ${{ inputs.POOL_NAME }}
      run: |
        pnpx saleor backup restore "$BACKUP_ID" \
          --environment="$INSTANCE_NAME" \
          --skip-webhooks-update

    - name: Create new instance
      shell: bash
      if: ${{ !steps.instance_check.outputs.INSTANCE_KEY }}
      env:
        BACKUP_ID: ${{ inputs.BACKUP_ID }}
        INSTANCE_NAME: ${{ inputs.POOL_NAME }}
        SALEOR_CLOUD_SERVICE: ${{ inputs.SALEOR_CLOUD_SERVICE }}
      run: |
        pnpx saleor env create "$INSTANCE_NAME" \
         --project=project-for-pr-testing \
         --database=snapshot \
         --restore-from="$BACKUP_ID" \
         --saleor="$SALEOR_CLOUD_SERVICE" \
         --domain="$INSTANCE_NAME" \
         --skip-restrict \
         --skip-webhooks-update

    - name: Add client origins
      shell: bash
      # Add base url as a trusted origins if we're using deployed dashboard in repo (saleor.rocks)
      if: ${{ !contains(inputs.BASE_URL, inputs.POOL_INSTANCE) }}
      env:
        POOL_NAME: ${{ inputs.POOL_NAME }}
        BASE_URL: ${{ inputs.BASE_URL }}
      run: |
        pnpx saleor env origins "$POOL_NAME" --origins="$BASE_URL"
