name: init-testmo
description: "Inits testmo reports"
inputs:
  testmoUrl:
    description: "Testmo project URL"
    required: true
  testmoToken:
    description: "Testmo token"
    required: true
  testmoRunName:
    description: "Displayed name in testmo"
    required: true

outputs:
  testmo-run-id:
    description: "Testmo run id"
    value: ${{ steps.run-tests.outputs.TESTMO_RUN_ID }}
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: npm
    - name: install dependencies
      working-directory: .github/workflows
      shell: bash
      run: npm ci
    - name: create testmo run
      working-directory: .github/workflows
      shell: bash
      run: |
        ID=$(npx testmo automation:run:create \
          --instance "$TESTMO_URL" \
          --project-id 1 \
          --name "$RUN_NAME" \
          --source frontend-e2e-tests)
        echo "TESTMO_RUN_ID=$ID" >> $GITHUB_OUTPUT
      env:
        TESTMO_URL: ${{ inputs.testmoUrl }}
        TESTMO_TOKEN: ${{ inputs.testmoToken }}
        RUN_NAME: ${{inputs.testmoRunName}}
      id: run-tests
