import {
  JobStatusEnum,
  MarkAsPaidStrategyEnum,
  OrderChargeStatusEnum,
  OrderDetailsFragment,
  OrderStatus,
  PaymentChargeStatusEnum,
} from "@dashboard/graphql";

export const fulfilledOrderFixture = {
  __typename: "Order",
  id: "order-id",
  status: OrderStatus.FULFILLED,
  number: "12345",
  created: "2023-10-01T12:00:00Z",
  isShippingRequired: true,
  canFinalize: false,
  customerNote:
    "This is a customer note. Lorem ipsum dolor sit amet. Consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  isPaid: true,
  paymentStatus: PaymentChargeStatusEnum.FULLY_CHARGED,
  shippingMethodName: "Standard Shipping",
  collectionPointName: null,
  actions: [],
  userEmail: "customer@example.com",
  chargeStatus: OrderChargeStatusEnum.FULL,
  billingAddress: {
    phone: "mocked-phone-number",
    cityArea: "",
    countryArea: "",
    __typename: "Address",
    city: "Wroclaw",
    id: "shipping-address-id",
    companyName: "Saleor",
    firstName: "Test",
    lastName: "Testowy",
    streetAddress1: "Teczowa 7",
    streetAddress2: "",
    postalCode: "53-000",
    country: {
      __typename: "CountryDisplay",
      code: "PL",
      country: "Poland",
    },
  },
  transactions: [],
  payments: [],
  giftCards: [],
  grantedRefunds: [],
  discounts: [],
  events: [],
  fulfillments: [],
  lines: [],
  shippingAddress: {
    phone: "mocked-phone-number",
    cityArea: "",
    countryArea: "",
    __typename: "Address",
    city: "Wroclaw",
    id: "shipping-address-id",
    companyName: "Saleor",
    firstName: "Test",
    lastName: "Testowy",
    streetAddress1: "Teczowa 7",
    streetAddress2: "",
    postalCode: "53-000",
    country: {
      __typename: "CountryDisplay",
      code: "PL",
      country: "Poland",
    },
  },
  deliveryMethod: null,
  shippingMethod: null,
  shippingPrice: {
    __typename: "TaxedMoney",
    gross: {
      __typename: "Money",
      amount: 10,
      currency: "USD",
    },
  },
  subtotal: {
    __typename: "TaxedMoney",
    gross: {
      __typename: "Money",
      amount: 100,
      currency: "USD",
    },
    net: {
      __typename: "Money",
      amount: 100,
      currency: "USD",
    },
  },
  total: {
    __typename: "TaxedMoney",
    gross: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
    net: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
    tax: {
      __typename: "Money",
      amount: 0,
      currency: "USD",
    },
  },
  totalRemainingGrant: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalGrantedRefund: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalRefundPending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalRefunded: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalAuthorizePending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalAuthorized: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalCaptured: {
    __typename: "Money",
    amount: 110,
    currency: "USD",
  },
  totalCharged: {
    __typename: "Money",
    amount: 110,
    currency: "USD",
  },
  totalChargePending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalCanceled: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalCancelPending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalBalance: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  undiscountedTotal: {
    __typename: "TaxedMoney",
    net: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
    gross: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
  },
  user: {
    __typename: "User",
    id: "user-id",
    email: "customer@example.com",
  },
  shippingMethods: [],
  invoices: [
    {
      __typename: "Invoice",
      id: "invoice-id-1",
      number: "INV-0001",
      status: JobStatusEnum.SUCCESS,
      createdAt: "2023-10-01T12:00:00Z",
      url: "https://example.com/invoice/1",
    },
    {
      __typename: "Invoice",
      id: "invoice-id-2",
      number: "INV-0002",
      status: JobStatusEnum.SUCCESS,
      createdAt: "2023-10-02T12:00:00Z",
      url: "https://example.com/invoice/2",
    },
  ],
  channel: {
    __typename: "Channel",
    id: "channel-id",
    name: "Default Channel",
    isActive: true,
    currencyCode: "USD",
    slug: "default-channel",
    defaultCountry: {
      __typename: "CountryDisplay",
      code: "US",
    },
    orderSettings: {
      __typename: "OrderSettings",
      markAsPaidStrategy: MarkAsPaidStrategyEnum.TRANSACTION_FLOW,
    },
  },
  metadata: [],
  privateMetadata: [],
} satisfies OrderDetailsFragment;
