import {
  LOGIN_SELECTORS,
  MENU_SELECTORS,
  SET_PASSWORD_SELECTORS,
} from "./account/";
import { APPS_LIST } from "./apps";
import { ATTRIBUTES_DETAILS, ATTRIBUTES_LIST } from "./attribute";
import {
  CATEGORIES_LIST,
  CATEGORY_DETAILS,
  COLLECTION_SELECTORS,
} from "./catalog";
import { CHANNELS_SELECTORS } from "./channels";
import { CONFIGURATION_SELECTORS } from "./configuration/configuration-selectors";
import { CUSTOMER_DETAILS, CUSTOMERS_LIST } from "./customer/";
import { SALES_SELECTORS, VOUCHERS_SELECTORS } from "./discounts";
import { DRAFT_ORDERS_LIST_SELECTORS, ORDERS_SELECTORS } from "./orders";
import { PAGE_DETAILS, PAGES_LIST } from "./pages/";
import { PAGE_TYPE_DETAILS, PAGE_TYPES_LIST } from "./pageTypes";
import {
  PERMISSION_GROUP_DETAILS,
  PERMISSION_GROUP_LIST,
} from "./permissionGroup";
import { PLUGINS_DETAILS, PLUGINS_LIST } from "./plugins";
import { PRODUCT_TYPE_DETAILS, PRODUCT_TYPES_LIST } from "./productTypes";
import { ADDRESS_SELECTORS, SHARED_ELEMENTS } from "./shared";
import { SHIPPING_ZONES_LIST } from "./shipping";
import {
  INVITE_STAFF_MEMBER_FORM,
  STAFF_MEMBER_DETAILS,
  STAFF_MEMBERS_LIST,
} from "./staffMembers";
import { LANGUAGES_LIST } from "./translations";

export {
  ADDRESS_SELECTORS,
  APPS_LIST,
  ATTRIBUTES_DETAILS,
  ATTRIBUTES_LIST,
  CATEGORIES_LIST,
  CATEGORY_DETAILS,
  CHANNELS_SELECTORS,
  COLLECTION_SELECTORS,
  CONFIGURATION_SELECTORS,
  CUSTOMER_DETAILS,
  CUSTOMERS_LIST,
  DRAFT_ORDERS_LIST_SELECTORS,
  INVITE_STAFF_MEMBER_FORM,
  LANGUAGES_LIST,
  LOGIN_SELECTORS,
  MENU_SELECTORS,
  ORDERS_SELECTORS,
  PAGE_DETAILS,
  PAGE_TYPE_DETAILS,
  PAGE_TYPES_LIST,
  PAGES_LIST,
  PERMISSION_GROUP_DETAILS,
  PERMISSION_GROUP_LIST,
  PLUGINS_DETAILS,
  PLUGINS_LIST,
  PRODUCT_TYPE_DETAILS,
  PRODUCT_TYPES_LIST,
  SALES_SELECTORS,
  SET_PASSWORD_SELECTORS,
  SHARED_ELEMENTS,
  SHIPPING_ZONES_LIST,
  STAFF_MEMBER_DETAILS,
  STAFF_MEMBERS_LIST,
  VOUCHERS_SELECTORS,
};
