import {
  LOGIN_SELECTORS,
  MENU_SELECTORS,
  SET_PASSWORD_SELECTORS,
} from "./account/";
import { APPS_LIST_SELECTORS } from "./apps";
import { ATTRIBUTES_DETAILS, ATTRIBUTES_LIST } from "./attribute";
import {
  CATEGORIES_LIST_SELECTORS,
  CATEGORY_DETAILS_SELECTORS,
  COLLECTION_SELECTORS,
} from "./catalog";
import { CHANNELS_SELECTORS } from "./channels";
import { CONFIGURATION_SELECTORS } from "./configuration/configuration-selectors";
import {
  CUSTOMER_DETAILS_SELECTORS,
  CUSTOMERS_LIST_SELECTORS,
} from "./customer/";
import { SALES_SELECTORS, VOUCHERS_SELECTORS } from "./discounts";
import { DRAFT_ORDERS_LIST_SELECTORS, ORDERS_SELECTORS } from "./orders";
import { PAGE_DETAILS_SELECTORS, PAGES_LIST_SELECTORS } from "./pages/";
import {
  PAGE_TYPE_DETAILS_SELECTORS,
  PAGE_TYPES_LIST_SELECTORS,
} from "./pageTypes";
import {
  PERMISSION_GROUP_DETAILS_SELECTORS,
  PERMISSION_GROUP_LIST_SELECTORS,
} from "./permissionGroup";
import { PLUGINS_DETAILS_SELECTORS, PLUGINS_LIST_SELECTORS } from "./plugins";
import {
  PRODUCT_TYPE_DETAILS_SELECTORS,
  PRODUCT_TYPES_LIST_SELECTORS,
} from "./productTypes";
import { ADDRESS_SELECTORS, SHARED_ELEMENTS } from "./shared";
import { SHIPPING_ZONES_LIST_SELECTORS } from "./shipping";
import {
  INVITE_STAFF_MEMBER_FORM_SELECTORS,
  STAFF_MEMBER_DETAILS_SELECTORS,
  STAFF_MEMBERS_LIST_SELECTORS,
} from "./staffMembers";
import { LANGUAGES_LIST_SELECTORS } from "./translations";

export {
  ADDRESS_SELECTORS,
  APPS_LIST_SELECTORS,
  ATTRIBUTES_DETAILS,
  ATTRIBUTES_LIST,
  CATEGORIES_LIST_SELECTORS,
  CATEGORY_DETAILS_SELECTORS,
  CHANNELS_SELECTORS,
  COLLECTION_SELECTORS,
  CONFIGURATION_SELECTORS,
  CUSTOMER_DETAILS_SELECTORS,
  CUSTOMERS_LIST_SELECTORS,
  DRAFT_ORDERS_LIST_SELECTORS,
  INVITE_STAFF_MEMBER_FORM_SELECTORS,
  LANGUAGES_LIST_SELECTORS,
  LOGIN_SELECTORS,
  MENU_SELECTORS,
  ORDERS_SELECTORS,
  PAGE_DETAILS_SELECTORS,
  PAGE_TYPE_DETAILS_SELECTORS,
  PAGE_TYPES_LIST_SELECTORS,
  PAGES_LIST_SELECTORS,
  PERMISSION_GROUP_DETAILS_SELECTORS,
  PERMISSION_GROUP_LIST_SELECTORS,
  PLUGINS_DETAILS_SELECTORS,
  PLUGINS_LIST_SELECTORS,
  PRODUCT_TYPE_DETAILS_SELECTORS,
  PRODUCT_TYPES_LIST_SELECTORS,
  SALES_SELECTORS,
  SET_PASSWORD_SELECTORS,
  SHARED_ELEMENTS,
  SHIPPING_ZONES_LIST_SELECTORS,
  STAFF_MEMBER_DETAILS_SELECTORS,
  STAFF_MEMBERS_LIST_SELECTORS,
  VOUCHERS_SELECTORS,
};
