name: Prepare backup variables
description: Prepare database snapshots
inputs:
  CLI_TOKEN:
    description: "Saleor cli token"
    required: true
  BACKUP_NAMESPACE:
    description: "The backups namespace"
    required: true
outputs:
  BACKUP_ID:
    description: "The ID of backup"
    value: ${{ steps.backup.outputs.BACKUP_ID }}
  BACKUP_VER:
    description: "The version of backup"
    value: ${{ steps.backup.outputs.BACKUP_VER }}
  BACKUP_NAME:
    description: "The name of backup"
    value: ${{ steps.backup.outputs.BACKUP_NAME }}
runs:
  using: "composite"
  steps:
    - name: Saleor login
      uses: ./.github/actions/cli-login
      with:
        token: ${{ inputs.CLI_TOKEN }}

    - name: Obtain backup id
      id: backup
      shell: bash
      env:
        SALEOR_CLI_ENV: staging
        BACKUP_NAME: ${{ inputs.BACKUP_NAMESPACE }}
      run: |
        BACKUPS=$(npx saleor backup list --name="$BACKUP_NAME" --latest --json)
        BACKUP_ID=$(echo "$BACKUPS" | jq -r '.[0].key')
        BACKUP_VER=$(echo "$BACKUPS" | jq -r '.[0].saleor_version')
        BACKUP_NAME=$(echo "$BACKUPS" | jq -r '.[0].name')

        echo "BACKUP_ID=$BACKUP_ID" >> $GITHUB_OUTPUT
        echo "BACKUP_VER=$BACKUP_VER" >> $GITHUB_OUTPUT
        echo "BACKUP_NAME=$BACKUP_NAME" >> $GITHUB_OUTPUT
