export const initialData = [
  {
    id: "1",
    uuid: "627bd0e7476cd1000ecef6b4",
    balance: { amount: 3067.88, currency: "EUR" },
    age: 40,
    eyeColor: "green",
    name: "Melba Keller",
    loan: {
      active: true,
      amount: 10.0,
      currency: "USD",
    },
    job: {
      label: "Engineer",
      value: "eng",
    },
  },
  {
    id: "2",
    uuid: "627bd0e763eb9e68f3800b9f",
    balance: { amount: 3523.57, currency: "EUR" },
    age: 39,
    eyeColor: "green",
    name: "Dixie Rivera",
    loan: {
      active: true,
      amount: 151.0,
      currency: "USD",
    },
    job: {
      label: "Engineer",
      value: "eng",
    },
  },
  {
    id: "3",
    uuid: "627bd0e785b17c7a9b406c62",
    balance: { amount: 3240.22, currency: "EUR" },
    age: 38,
    eyeColor: "brown",
    name: "Lamb Clayton",
    loan: {
      active: true,
      amount: 21.0,
      currency: "USD",
    },
    job: {
      label: "Director",
      value: "director",
    },
  },
  {
    id: "4",
    uuid: "627bd0e7c6460044c736e00a",
    balance: { amount: 3450.59, currency: "EUR" },
    age: 30,
    eyeColor: "blue",
    name: "Charity Mcgee",
    loan: {
      active: true,
      amount: 52.0,
      currency: "USD",
    },
    job: {
      label: "QA",
      value: "qa",
    },
  },
  {
    id: "5",
    uuid: "627bd0e77792e92a1b00d09c",
    balance: { amount: 3196.74, currency: "EUR" },
    age: 39,
    eyeColor: "brown",
    name: "Ward Hayden",
    loan: {
      active: true,
      amount: 991.0,
      currency: "USD",
    },
    job: {
      label: "QA",
      value: "qa",
    },
  },
  {
    id: "6",
    uuid: "627bd0e78ff0fc7e94570ecd",
    balance: { amount: 2222.02, currency: "EUR" },
    age: 30,
    eyeColor: "blue",
    name: "Emily Parrish",
    loan: {
      active: true,
      amount: 82.0,
      currency: "USD",
    },
    job: {
      label: "QA",
      value: "qa",
    },
  },
  {
    id: "7",
    uuid: "627bd0e7d0b1a0050a83619b",
    balance: { amount: 3558.55, currency: "EUR" },
    age: 37,
    eyeColor: "blue",
    name: "Wood Hensley",
    loan: {
      active: false,
      amount: null,
      currency: "USD",
    },
    job: {
      label: "Engineer",
      value: "eng",
    },
  },
  {
    id: "8",
    uuid: "627bd0e7138637a41c457158",
    balance: { amount: 1955.85, currency: "EUR" },
    age: 29,
    eyeColor: "green",
    name: "Karin Cote",
    loan: {
      active: true,
      amount: 1.1,
      currency: "USD",
    },
    job: {
      label: "Designer",
      value: "designer",
    },
  },
  {
    id: "9",
    uuid: "627bd0e7c3502435bc459efe",
    balance: { amount: -2358.54, currency: "EUR" },
    age: 37,
    eyeColor: "green",
    name: "Roberta Rollins",
    loan: {
      active: true,
      amount: 1000.0,
      currency: "USD",
    },
    job: {
      label: "Designer",
      value: "designer",
    },
  },
  {
    id: "10",
    uuid: "627bd0e7da2e10b6154b85cf",
    balance: { amount: 2048.1, currency: "EUR" },
    age: 26,
    eyeColor: "green",
    name: "Francis Talley",
    loan: {
      active: false,
      amount: null,
      currency: "USD",
    },
    job: {
      label: "Manager",
      value: "manager",
    },
  },
];
