name: Create-check
description: "Creates check for PR"
inputs:
  PR_HEAD:
    description: "Head of PR on which create check"
    required: true
  CHECK_NAME:
    description: "Name of check"
    required: true
  STATUS:
    description: "Status of check"
    required: true
  TITLE: 
    description: "Title of check"
    required: true
  DETAILS_URL: 
    description: "Details url"
    required: true

outputs:
  CHECK_ID:
    description: "CHECK_ID"
    value: ${{ steps.create-check.outputs.check_id }}

runs:
  using: composite
  steps:
    - name: Get Pull Request head_sha
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        PR_HEAD: ${{ inputs.PR_HEAD }}
      run: |
        gh api \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "/repos/saleor/saleor-dashboard/pulls?head=saleor:${PR_HEAD}" > data.json
        echo "PULL_REQUEST_HEAD_SHA=$(jq '.[0] | .head.sha' data.json)" >> $GITHUB_ENV

    - name: Create check
      if: ${{ env.PULL_REQUEST_HEAD_SHA }}
      shell: bash
      id: create-check
      env:
        GH_TOKEN: ${{ github.token }}
        NAME: ${{ inputs.CHECK_NAME }}
        STATUS: ${{ inputs.STATUS }}
        TITLE: ${{ inputs.TITLE }}
      run: |
        payload=$(\
        jq --null-input \
        --arg name "$NAME" \
        --arg head_sha "$PULL_REQUEST_HEAD_SHA" \
        --arg status "$STATUS" \
        --arg title "$TITLE" \
        --arg details_url "$DETAILS_URL" \
        '{
          "name": $name, 
          "head_sha": $head_sha, 
          "status": $status, 
          "output": {
            "title": $title,
            "summary": "",
            "text": "",
            "details_url": $details_url
         }
        }'
        )

        check_id=$(curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/saleor/saleor-dashboard/check-runs \
        -d "$payload" | jq -r '.id') ; echo "check_id=$check_id" >> $GITHUB_OUTPUT

        echo $check_id