name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: textarea
    id: Description
    attributes:
      label: Description of the issue
      description: Describe your goal, use case, or provide context of your problem.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Reproduction steps.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Describe why the behavior described earlier is incorrect.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Include any logs from the console, screenshots that could help us understand the problem. Make sure to omit any personal identifiable information or data sensitive to your business.
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide some information about your environment.
      value: |
        Browser and version: …
        OS and version: …
        Dashboard version: …
        Core version: …
    validations:
      required: true
