blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/saleor/dashboard/discussions
    about: If you have a support question or need help getting dashboard to work, please use GitHub Discussions.
