blank_issues_enabled: false
contact_links:
  - name: 💬 Discord
    url: https://saleor.io/discord
    about: If you have a support question or need help getting dashboard to work, please use Discord.
