name: Enhancement request
description: "Small scope enhancements that do not alter the behavior of the product: Spelling, text adjustments, translations, documentation, small visual design corrections, icon adjustments, etc."
title: "[Enhancement]: "
labels: ["enhancement", "backlog"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the enhancement
      description: Describe what you want to improve, attach the reasoning.
      placeholder: |
        Example: I want to adjust the border colors as well as inner padding to be consistent with the other views
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Attach some additional context. Links, references, UI mockups and so on.
      placeholder: |
        Example:
        Here are the mockups for this datagrid.
        We consider keeping it simple and similar to the ordinary table.
        Please look at the attached screenshots:
        ...
    validations:
      required: false

