name: Epic request
description: Publish a new group of issues
title: "[Epic]: "
labels: ["epic"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description of an epic
      description: Describe overall goal, provide context, explain what goal it represents
      placeholder: |
        Example: Users needs to have variant edition functionality. This is essential for managing eCommerce and needs lots of configuration for each variant.
        We must consider its attributes, quantities, correlated channels and more. 
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Attach some additional context.
      placeholder: |
        Example:
        Here are the example mockups for variant edition.
        Let's consider what options it supposed to have.
        Please look at the attached references - it explains how marked use it.
        ...
    validations:
      required: false

