name: Feature request
description: Publish a new feature request
title: "[Feature]: "
labels: ["feature"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the feature
      description: Describe your goal, use case, or provide context.
      placeholder: |
        Example: Users can be more productive when we allow them to bulk update multiple variants at once.
        We can implement datagrid table that presents all variants, and when clicking in some cell, it will turn into edit mode.
    validations:
      required: true
  - type: textarea
    id: acceptable-criteria
    attributes:
      label: Acceptable criteria
      description: Provide acceptable criteria for this feature. Describe expected behavior against personas.
      placeholder: |
        Example:
        - [ ] As user, I should see all variands presented in the datagrid table
        - [ ] As user, I should enable edit mode on a given cell when i double-click on it
        - [ ] As user, I am able to edit multiple cell and save them at once
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Attach some additional context. Links, references, UI mockups and so on.
      placeholder: |
        Example:
        Here are the mockups for this datagrid.
        We consider to keep it simple and similar to the ordinary table.
        Please look at the attached screenshots:
        ...
    validations:
      required: false

