name: Feature request
description: "Broader scope requests, a new implementation that is not yet present in the project."
title: "[Feature]: "
labels: ["feature", "backlog"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description of the feature
      description: Describe your goal, use case, or provide context.
      placeholder: |
        Example: Users can be more productive when we allow them to bulk update multiple variants at once.
        We can implement datagrid table that presents all variants, and when clicking in some cell, it will turn into edit mode.
    validations:
      required: true
  - type: input
    id: discord-discussion
    attributes:
      label: Discord Discussion Link
      description: Link to a corresponding thread in the [Discord](https://saleor.io/discord)'s "#ideas" channel. Read more about the process in the [Contribution Guidelines](http://docs.saleor.io/developer/community/contributing#contributing-issues).
      placeholder: https://discord.com/channels/8640668198...
    validations:
      required: true
  - type: textarea
    id: acceptable-criteria
    attributes:
      label: Acceptable criteria
      description: Provide acceptable criteria for this feature. Describe expected behavior against personas.
      placeholder: |
        Example:
        - [ ] As a user, I should see all variants presented in the datagrid table
        - [ ] As a user, I should enable edit mode on a given cell when I double-click on it
        - [ ] As a user, I am able to edit multiple cells and save them at once
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Attach some additional context. Links, references, UI mockups and so on.
      placeholder: |
        Example:
        Here are the mockups for this datagrid.
        We consider keeping it simple and similar to the ordinary table.
        Please look at the attached screenshots:
        ...
    validations:
      required: false
