name: RFC
description: Start gathering information regarding new functionality
title: "[RFC]: "
labels: [RFC]
assignees:
  - andrzejewski
  - krzysztofzuraw
body:
  - type: textarea
    id: introduction
    attributes:
      label: Short description of the feature
      description: Provide short description of the future, its intention, what problem it solves.
      placeholder: |
        - What problem does it solve?
        - What feature should generally do?
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Full description
      description: Provide full description of a given feature. Provide as much details as you can.
      placeholder: |
        Explain in details:
        - What feature should do
        - How certain UI should look like
        - How UI should change depending on the context eg. different permissions, different resource data
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define Acceptance Criteria
      placeholder: |
        - As user I should ...
        - As developer I can ...
        - When the user switches X to Y, the Z should be displayed...
      render: Markdown
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional notes
      description: Write down any additional notes
      placeholder: |
        - Paste important link
        - Define additional action points
        - Define your concerns
      render: Markdown
    validations:
      required: false
