export const PRODUCT_DETAILS = {
  productNameInput: "[name='name']",
  productTypeInput: "[data-test='product-type']",
  categoryInput: "[data-test='category']",
  categoryItem: "[data-test-id='singleautocomplete-select-option']",
  collectionInput: "[data-test='collections']",
  autocompleteDropdown: "[data-test='autocomplete-dropdown']",
  firstCategoryItem: "#downshift-0-item-0",
  visibleRadioBtn: "[name='isPublished']",
  channelAvailabilityItem: "[data-test='channel-availability-item']",
  addVariantsButton: "[data-test*='button-add-variant']",
  addVariantsOptionDialog: {
    optionMultiple: '[data-test-id="variant-create-option-multiple"]',
    optionSingle: '[data-test-id="variant-create-option-single"]'
  },
  descriptionInput: "[data-test-id='description']",
  ratingInput: "[name='rating']",
  skuInput: "[name='sku']",
  variantRow: "[data-test-id='product-variant-row']",
  variantPrice: '[data-test="price"]',
  collectionRemoveButtons: '[data-test-id="collectionRemove"]',
  productImage: '[data-test="product-image"]',
  uploadImageButton: '[data-test="button-upload-image"]',
  uploadSavedImagesButton: '[data-test="uploadImages"]',
  uploadMediaUrlButton: '[data-test="uploadMediaUrl"]',
  saveUploadUrlButton: '[data-test-id="upload-url-button"]',
  addWarehouseButton: '[data-test-id="add-warehouse"]',
  warehouseOption: "[role='menuitem']",
  stockInput: '[data-test-id="stock-input"]',
  costPriceInput: '[name*="costPrice"]',
  sellingPriceInput: '[name*="channel-price"]',
  createSingleVariantCheckbox: '[value="single"]'
};
