export const PRODUCT_DETAILS = {
  productNameInput: "[name='name']",
  productTypeInput: "[data-test-id='product-type']",
  categoryInput: "[data-test-id='category']",
  categoryItem: "[data-test-id='single-autocomplete-select-option']",
  collectionInput: "[data-test-id='collections']",
  autocompleteDropdown: "[data-test-id='autocomplete-dropdown']",
  firstCategoryItem: "#downshift-0-item-0",
  visibleRadioBtn: "[name='isPublished']",
  channelAvailabilityItem: "[data-test-id*='channel-availability-item']",
  addVariantButton: "[data-test-id*='button-add-variant']",
  descriptionInput: "[data-test-id='rich-text-editor-description']",
  ratingInput: "[name='rating']",
  skuInput: "[name='sku']",
  variantRow: "[data-test-id='product-variant-row']",
  variantPrice: '[data-test-id="price"]',
  collectionRemoveButtons: '[data-test-id="collection-remove"]',
  addWarehouseButton: '[data-test-id="add-warehouse"]',
  warehouseOption: "[role='menuitem']",
  stockInput: '[data-test-id="stock-input"]',
  costPriceInput: '[name*="costPrice"]',
  sellingPriceInput: '[name*="channel-price"]',
  productImage: '[data-test-id="product-image"]',
  uploadImageButton: '[data-test-id="button-upload-image"]',
  uploadSavedImagesButton: '[data-test-id="upload-images"]',
  uploadMediaUrlButton: '[data-test-id="upload-media-url"]',
  saveUploadUrlButton: '[data-test-id="upload-url-button"]',
};
