name: Prepare tests variables
description: Prepare database snapshots
inputs:
  MODE:
    description: "The mode of running tests (pull-request, release, main)"
    required: true
  CLI_TOKEN:
    description: "Saleor cli token"
    required: true
  VERSION:
    description: "Version in format X.XX, if run from other branch"
    required: false

outputs:
  BASE_URL:
    description: "Dashboard base url"
    value: ${{ steps.api.outputs.BASE_URL }}
  BASE_URL_DOMAIN:
    description: "Dashboard domain"
    value: ${{ steps.api.outputs.BASE_URL_DOMAIN }}
  API_URL:
    description: "API url"
    value: ${{ steps.api.outputs.API_URL }}
  POOL_NAME:
    description: "The name of the instance"
    value: ${{ steps.api.outputs.POOL_NAME }}
  POOL_INSTANCE:
    description: "The full URL of the instance"
    value: ${{ steps.api.outputs.POOL_INSTANCE }}
  BACKUP_ID:
    description: "The ID of backup"
    value: ${{ steps.backup.outputs.BACKUP_ID }}
  BACKUP_VER:
    description: "The version of backup"
    value: ${{ steps.backup.outputs.BACKUP_VER }}
  BACKUP_NAME:
    description: "The name of backup"
    value: ${{ steps.backup.outputs.BACKUP_NAME }}
  BACKUP_NAMESPACE:
    description: "The name of backup"
    value: ${{ steps.api.outputs.BACKUP_NAMESPACE }}
runs:
  using: "composite"
  steps:
    - name: Generate api
      id: api
      uses: ./.github/actions/prepare-api-variables
      with:
        MODE: ${{ inputs.MODE }}
        VERSION: ${{ inputs.VERSION || ''}} 
  
    - name: Generate backup
      id: backup
      uses: ./.github/actions/prepare-backups-variables
      with:
        CLI_TOKEN: ${{ inputs.CLI_TOKEN }}
        BACKUP_NAMESPACE: ${{ steps.api.outputs.BACKUP_NAMESPACE }}

    - name: Print annotations
      shell: bash
      env:
        BASE_URL: ${{ steps.api.outputs.BASE_URL }}
        API_URL: ${{ steps.api.outputs.API_URL }}
        POOL_NAME: ${{ steps.api.outputs.POOL_NAME }}
        POOL_INSTANCE: ${{ steps.api.outputs.POOL_INSTANCE }}
        BACKUP_ID: ${{ steps.backup.outputs.BACKUP_ID }}
        BACKUP_VER: ${{ steps.backup.outputs.BACKUP_VER }}
        BACKUP_NAME: ${{ steps.backup.outputs.BACKUP_NAME }}
        BACKUP_NAMESPACE: ${{ steps.api.outputs.BACKUP_NAMESPACE }}
      run: |
        echo "::notice title=BASE_URL::${BASE_URL}"
        echo "::notice title=API_URL::${API_URL}"
        echo "::notice title=POOL_NAME::${POOL_NAME}"
        echo "::notice title=POOL_INSTANCE::${POOL_INSTANCE}"
        echo "::notice title=BACKUP_NAMESPACE::${BACKUP_NAMESPACE}"
        echo "::notice title=SNAPSHOT::backup_id=${BACKUP_ID}, version=${BACKUP_VER}, name=${BACKUP_NAME}"