import {
  MarkAsPaidStrategyEnum,
  OrderChargeStatusEnum,
  OrderDetailsFragment,
  OrderStatus,
  PaymentChargeStatusEnum,
} from "@dashboard/graphql";

export const fulfilledOrderFixture = {
  __typename: "Order",
  id: "order-id",
  status: OrderStatus.FULFILLED,
  number: "12345",
  created: "2023-10-01T12:00:00Z",
  isShippingRequired: true,
  canFinalize: false,
  customerNote: "",
  isPaid: true,
  paymentStatus: PaymentChargeStatusEnum.FULLY_CHARGED,
  shippingMethodName: "Standard Shipping",
  collectionPointName: null,
  actions: [],
  userEmail: "customer@example.com",
  chargeStatus: OrderChargeStatusEnum.FULL,
  billingAddress: null,
  transactions: [],
  payments: [],
  giftCards: [],
  grantedRefunds: [],
  discounts: [],
  events: [],
  fulfillments: [],
  lines: [],
  shippingAddress: null,
  deliveryMethod: null,
  shippingMethod: null,
  shippingPrice: {
    __typename: "TaxedMoney",
    gross: {
      __typename: "Money",
      amount: 10,
      currency: "USD",
    },
  },
  subtotal: {
    __typename: "TaxedMoney",
    gross: {
      __typename: "Money",
      amount: 100,
      currency: "USD",
    },
    net: {
      __typename: "Money",
      amount: 100,
      currency: "USD",
    },
  },
  total: {
    __typename: "TaxedMoney",
    gross: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
    net: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
    tax: {
      __typename: "Money",
      amount: 0,
      currency: "USD",
    },
  },
  totalRemainingGrant: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalGrantedRefund: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalRefundPending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalRefunded: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalAuthorizePending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalAuthorized: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalCaptured: {
    __typename: "Money",
    amount: 110,
    currency: "USD",
  },
  totalCharged: {
    __typename: "Money",
    amount: 110,
    currency: "USD",
  },
  totalChargePending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalCanceled: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalCancelPending: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  totalBalance: {
    __typename: "Money",
    amount: 0,
    currency: "USD",
  },
  undiscountedTotal: {
    __typename: "TaxedMoney",
    net: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
    gross: {
      __typename: "Money",
      amount: 110,
      currency: "USD",
    },
  },
  user: null,
  shippingMethods: [],
  invoices: [],
  channel: {
    __typename: "Channel",
    id: "channel-id",
    name: "Default Channel",
    isActive: true,
    currencyCode: "USD",
    slug: "default-channel",
    defaultCountry: {
      __typename: "CountryDisplay",
      code: "US",
    },
    orderSettings: {
      __typename: "OrderSettings",
      markAsPaidStrategy: MarkAsPaidStrategyEnum.TRANSACTION_FLOW,
    },
  },
  metadata: [],
  privateMetadata: [],
} satisfies OrderDetailsFragment;
