import { VOUCHERS_AND_DISCOUNTS } from "@data/e2eTestData";
import { VouchersPage } from "@pages/vouchersPage";
import { expect, test } from "@playwright/test";

test.use({ storageState: "playwright/.auth/admin.json" });

let vouchersPage: VouchersPage;

test.beforeEach(({ page }) => {
  vouchersPage = new VouchersPage(page);
});

test("TC: SALEOR_40 Create voucher with auto-generated codes and fixed amount discount @vouchers @e2e", async () => {
  const codesQuantity = 5;
  const codesPrefix = "auto";

  await vouchersPage.gotoVouchersListPage();
  await vouchersPage.clickCreateVoucherButton();
  await vouchersPage.typeVoucherName();
  await vouchersPage.clickAddCodeButton();
  await vouchersPage.clickAutoGeneratedCodesItem();
  await vouchersPage.addVoucherCodeDialog.typeCodesQuantity(
    codesQuantity.toString(),
  );
  await vouchersPage.addVoucherCodeDialog.typeCodesPrefix(codesPrefix);
  await vouchersPage.addVoucherCodeDialog.clickConfirmButton();
  await vouchersPage.waitForGrid();

  const generatedCodesRows = await vouchersPage.getNumberOfGridRowsWithText(
    codesPrefix,
  );

  await expect(
    generatedCodesRows,
    `Auto-generated number of codes: ${codesQuantity} should be visible on grid`,
  ).toEqual(codesQuantity);

  await vouchersPage.typeDiscountValueInChannel();
  await vouchersPage.clickSaveButton();
  await vouchersPage.expectSuccessBanner();
  await vouchersPage.waitForGrid();
  const activeCodesRows = await vouchersPage.getNumberOfGridRowsWithText(
    "Active",
  );
  await expect(
    activeCodesRows,
    `Given codes quantity: ${codesQuantity} should have status Active displayed on grid`,
  ).toEqual(codesQuantity);
});

test("TC: SALEOR_85 Create voucher with manual code and percentage discount @vouchers @e2e", async () => {
  const code = `code-TC: SALEOR_85 ${new Date().toISOString()}`;

  await vouchersPage.gotoVoucherAddPage();
  await vouchersPage.typeVoucherName();
  await vouchersPage.clickAddCodeButton();
  await vouchersPage.clickManualGeneratedCodesItem();
  await vouchersPage.addVoucherCodeDialog.typeCode(code);
  await vouchersPage.addVoucherCodeDialog.clickConfirmButton();
  await vouchersPage.waitForGrid();

  const manualCodesRows = await vouchersPage.getNumberOfGridRowsWithText(code);

  await expect(
    manualCodesRows,
    `Manually added code: ${code} should be visible on grid`,
  ).toEqual(1);

  await vouchersPage.clickPercentDiscountTypeButton();
  await vouchersPage.typeDiscountValueInChannel("Channel-PLN", "50");
  await vouchersPage.clickSaveButton();

  await vouchersPage.expectSuccessBanner();
  await vouchersPage.waitForGrid();
  const manualActiveCodesRows = await vouchersPage.getNumberOfGridRowsWithText(
    "Active",
  );

  await expect(
    manualActiveCodesRows,
    `Given codes: ${code} should have status Active displayed on grid`,
  ).toEqual(1);
});

test("TC: SALEOR_86 Edit voucher to have free shipping discount @vouchers @e2e", async () => {
  await vouchersPage.gotoExistingVoucherPage(
    VOUCHERS_AND_DISCOUNTS.vouchers.voucherToBeEditedWithFreeShipping.id,
  );
  await vouchersPage.waitForGrid();
  const codesRows = await vouchersPage.getNumberOfGridRows();

  await vouchersPage.clickFreeShippingDiscountTypeButton();

  await expect(
    vouchersPage.discountValueInput,
    "No discount value input should be visible with free shipping type active ",
  ).not.toBeVisible();

  await vouchersPage.clickSaveButton();
  await vouchersPage.waitForGrid();

  await vouchersPage.expectSuccessBanner();
  const codesRowsAfterSave = await vouchersPage.getNumberOfGridRows();

  await expect(
    codesRows,
    `Same amount of codes should have status Active displayed on grid after switching to free shipping`,
  ).toEqual(codesRowsAfterSave);
});
test("TC: SALEOR_87 Edit voucher Usage Limits: used in total, per customer, staff only, code used once @vouchers @e2e", async () => {
  await vouchersPage.gotoExistingVoucherPage(
    VOUCHERS_AND_DISCOUNTS.vouchers.voucherToBeEditedUsageLimits.id,
  );
  await vouchersPage.waitForGrid();

  await vouchersPage.clickUsageTotalLimitCheckbox();
  await vouchersPage.typeUsageLimit("100000");
  await vouchersPage.clickOncePerCustomerLimitCheckbox();
  await vouchersPage.clickOnlyForStaffLimitCheckbox();
  await vouchersPage.clickSingleUseLimitCheckbox();
  await vouchersPage.clickSaveButton();
  await vouchersPage.waitForGrid();

  await vouchersPage.expectSuccessBanner();
  expect(
    await vouchersPage.usageLimitSection
      .locator('[class*="Mui-checked"]')
      .count(),
    "All usage limit checkboxes should be checked",
  ).toEqual(4);
});
