#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Maximum allowed branch name length (cloud limit)
MAX_LENGTH=37

# Check if the branch name length exceeds the maximum allowed length
branch_name=$(git symbolic-ref --short HEAD)
if [ ${#branch_name} -gt $MAX_LENGTH ]; then
    echo "⚠️  Warning: Branch name '$branch_name' exceeds the maximum allowed length of $MAX_LENGTH characters."
    echo "⚠️  Cloud instance will not be able to deploy."
fi

npm run check-types
npm run test
