name: test-workflow

on: [pull_request]

jobs:

  test-cli:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install saleor cli
        id: install-saleor-cli
        run: npm i -g @saleor/cli

      - name: Write config file
        id: write-config-file
        env:
          ACCESS_TOKEN: ${{ secrets.CLOUD_ACCESS_TOKEN }}
        run: echo '{"token":"Token ${{ secrets.CLOUD_ACCESS_TOKEN }}","telemetry":"false","organization_slug":"qa","organization_name":"QA","environment_id":"YrDtS7TT"}' > ~/.config/saleor.json

      - name: revert snapshot
        env:
          SALEOR_CLI_ENV: staging
        run: saleor backup restore 6tOoEwCh

  