name: test-workflow

on: [pull_request]

jobs:

  test-cli:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install saleor cli
        id: install-saleor-cli
        run: npm i -g @saleor/cli

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules-cli
        with:
          path: ~/.npm
          key: ${{ runner.os }}-qa-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-qa-${{ env.cache-name }}-
            ${{ runner.os }}-qa-
            ${{ runner.os }}-
      - name: Write config file
        id: write-config-file
        env:
          ACCESS_TOKEN: ${{ secrets.CLOUD_ACCESS_TOKEN }}
        run: echo '{"token":"Token ${{ secrets.CLOUD_ACCESS_TOKEN }}","telemetry":"false","organization_slug":"qa","organization_name":"QA","environment_id":"YrDtS7TT"}' > ~/.config/saleor.json

      - name: revert snapshot
        env:
          SALEOR_CLI_ENV: staging
        run: npx saleor backup restore 6tOoEwCh --skip-webhooks-update

  