on:
  release:
    types: [published]

permissions: {}

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Announce to Discord
        uses: SethCohen/github-releases-to-discord@6ac5abea42b8cbac14316970819a8a535aab08ea # v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "15105570"
          content: "New Saleor Dashboard release!"
