name: Execute percy demo tests

on:
  workflow_dispatch:
    inputs:
      dashboardUrl:
        description: 'Environment to run tests against'
        required: true
        default: 'https://staging-demo.saleor.io/dashboard/'
      apiUrl:
        required: true 
        description: 'Environment api to run tests against'
        default: 'https://staging-demo.saleor.io/graphql/'

  schedule:
    - cron: '00 2 * * 1-5'

  pull_request:
    types: [opened, reopened, synchronize, labeled]

  repository_dispatch:
    types: [demo-tests]

jobs:
  cypress-run-test-percy:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome106-ff106

    steps:
      - name: Get environments urls
        id: get-env-urls
        env:
          DEFAULT_DASHBOARD_URL: 'https://staging-demo.saleor.io/dashboard/'
          DEFAULT_API_URL: 'https://staging-demo.saleor.io/graphql/'
        run: |
          echo "DASHBOARD_URL=${{ github.event.inputs.dashboardUrl || env.DEFAULT_DASHBOARD_URL }}" >> $GITHUB_OUTPUT
          echo "API_URL=${{ github.event.inputs.apiUrl || env.DEFAULT_API_URL }}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: NODE_OPTIONS=--max_old_space_size=4096 npm install 

      - name: Cypress run test percy
        uses: cypress-io/github-action@v4
        env:
          API_URI: ${{ steps.get-env-urls.outputs.API_URL }}
          APP_MOUNT_URI: ${{ secrets.APP_MOUNT_URI }}
          CYPRESS_DEMO_URI: ${{ steps.get-env-urls.outputs.DASHBOARD_URL }}
          CYPRESS_USER_NAME: admin@example.com
          CYPRESS_USER_PASSWORD: admin
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: Percy - Demo dashboard tests - ${GITHUB_REF##*/} - ${{github.event.inputs.dashboardUrl}}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          group: "UI - Chrome"
          record: true
          command: npm run cy:percy