name: QA

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  if_merged:
    permissions:
      pull-requests: read
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      labels: ${{ steps.get_labels.outputs.labels }}
    steps:
      - name: Get PR labels
        id: get_labels
        uses: joerick/pr-labels-action@7beda983e70efd41dd55ef246d0b3bba82820f4c # v1.0.8

  chromatic-storybook-main:
    runs-on: ubuntu-latest
    needs: if_merged
    if: ${{ contains(needs.if_merged.outputs.labels, ' run-chromatic ') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-qa-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-qa-${{ env.cache-name }}-
            ${{ runner.os }}-qa-
            ${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: Publish to Chromatic and auto accept changes
        uses: chromaui/action@a89b674adf766dbde41ad9ea2b2b60b91188a0f0 # v6.17.4
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true
