import { type InstalledExtension } from "@dashboard/extensions/types";
import { AppTypeEnum } from "@dashboard/graphql";
import type { Meta, StoryFn, StoryObj } from "@storybook/react-vite";
import { Mail } from "lucide-react";
import { fn } from "storybook/test";

import { criticalAppProblem, warningAppProblem } from "../AppProblems/fixtures";
import { AppDisabledInfo } from "../InfoLabels/AppDisabledInfo";
import { InstalledExtensionsList } from "./InstalledExtensionsList";

const baseExtension: InstalledExtension = {
  id: "app-1",
  name: "Customer Emails",
  logo: <Mail size={20} />,
  info: null,
  href: "/extensions/app/app-1",
  appType: AppTypeEnum.THIRDPARTY,
  isActive: true,
  problems: [],
  activeProblemCount: 0,
  criticalProblemCount: 0,
};

const installedExtensions: InstalledExtension[] = [
  { ...baseExtension, id: "app-1", name: "Customer Emails" },
  {
    ...baseExtension,
    id: "app-2",
    name: "SMTP",
    deprecated: true,
    deprecationReason:
      "SMTP is replaced by Customer Emails. Install Customer Emails from Extensions, copy your templates over, then uninstall this app.",
  },
  {
    ...baseExtension,
    id: "app-3",
    name: "Product Feed",
    isActive: false,
    info: <AppDisabledInfo />,
    problems: [warningAppProblem],
    activeProblemCount: 1,
    deprecated: true,
    deprecationReason:
      "Product Feed is replaced by Google Merchant Center, which syncs products automatically instead of serving a static feed. Install Google Merchant Center from Extensions and point your Merchant Center account at it; feeds generated by this app stop updating once you uninstall it.",
  },
  { ...baseExtension, id: "app-4", name: "Legacy Invoices", deprecated: true },
  {
    ...baseExtension,
    id: "app-5",
    name: "Avatax",
    problems: [criticalAppProblem],
    activeProblemCount: 1,
    criticalProblemCount: 1,
  },
];

const meta: Meta<typeof InstalledExtensionsList> = {
  title: "Extensions/InstalledExtensionsList",
  component: InstalledExtensionsList,
  // The list bleeds 24px into the card padding on the page.
  decorators: [
    (Story: StoryFn) => (
      <div style={{ padding: "0 24px" }}>
        <Story />
      </div>
    ),
  ],
  args: {
    installedExtensions,
    loading: false,
    clearSearch: fn(),
    hasManagedAppsPermission: true,
    onClearProblem: fn(),
  },
};

export default meta;

type Story = StoryObj<typeof InstalledExtensionsList>;

export const WithDeprecatedApps: Story = {};
